// ─── CARAXES Catalogues par Profil Client ───
// Chaque profil (grossiste, détaillant, e-commerce) a son propre catalogue
// avec des catégories, prix, MOQ et produits phares adaptés

export const CATALOGS = {
  // ═══════════════════════════════════════════
  // GROSSISTE — Volumes, prix usine, palettes
  // ═══════════════════════════════════════════
  grossiste: [
    {
      id: 'alimentaire-vrac',
      name: 'Alimentaire en vrac',
      icon: '🥫',
      description: 'Conserves, sauces, huiles, céréales, légumineuses en gros conditionnement',
      priceRange: '0.80-5€',
      moq: 500,
      margin: '×2 à ×3',
      topProducts: ['Huile d\'olive 5L', 'Concentré tomate cartons', 'Riz basmati 25kg', 'Thon conserve palettes'],
      locations: ['Yiwu', 'Guangzhou'],
    },
    {
      id: 'textile-gros',
      name: 'Textile en gros',
      icon: '👕',
      description: 'T-shirts blancs, abayas basiques, foulards, sous-vêtements par cartons',
      priceRange: '1.50-8€',
      moq: 300,
      margin: '×2.5 à ×4',
      topProducts: ['T-shirts unis cartons 100', 'Abayas basiques lot', 'Hijabs mousseline gros', 'Chaussettes lot 200'],
      locations: ['Guangzhou', 'Yiwu'],
    },
    {
      id: 'cosmetique-gros',
      name: 'Cosmétique & Parfumerie',
      icon: '🧴',
      description: 'Parfums génériques, soins capillaires, crèmes, savons en gros volumes',
      priceRange: '0.50-6€',
      moq: 500,
      margin: '×3 à ×6',
      topProducts: ['Parfums génériques 100ml', 'Huile d\'argan 1L', 'Savon noir cartons', 'Henné naturel kg'],
      locations: ['Guangzhou', 'Yiwu'],
    },
    {
      id: 'electromenager',
      name: 'Petit électroménager',
      icon: '⚡',
      description: 'Bouilloires, mixeurs, grille-pains, ventilateurs en palettes',
      priceRange: '5-25€',
      moq: 100,
      margin: '×2 à ×3',
      topProducts: ['Bouilloires 1.7L', 'Mixeurs plongeants', 'Machines à café turque', 'Ventilateurs colonne'],
      locations: ['Shenzhen', 'Guangzhou'],
    },
    {
      id: 'emballage-packaging',
      name: 'Emballage & Packaging',
      icon: '📦',
      description: 'Barquettes, sacs kraft, film alimentaire, boîtes carton personnalisées',
      priceRange: '0.02-0.50€',
      moq: 5000,
      margin: '×3 à ×5',
      topProducts: ['Barquettes alu 1000pcs', 'Sacs kraft personnalisés', 'Boîtes pâtisserie', 'Film étirable palettes'],
      locations: ['Yiwu', 'Guangzhou'],
    },
    {
      id: 'bazar-general',
      name: 'Bazar & Divers',
      icon: '🏷️',
      description: 'Articles ménagers, vaisselle, outils, jouets, tout pour le bazar de quartier',
      priceRange: '0.20-5€',
      moq: 500,
      margin: '×3 à ×6',
      topProducts: ['Vaisselle mélamine lots', 'Briquets cartons 500', 'Accessoires ménage', 'Jouets enfants lots'],
      locations: ['Yiwu'],
    },
    {
      id: 'epices-condiments',
      name: 'Épices & Condiments',
      icon: '🌶️',
      description: 'Épices en vrac (cumin, curcuma, paprika), sauces, vinaigres',
      priceRange: '1-8€',
      moq: 200,
      margin: '×2.5 à ×4',
      topProducts: ['Cumin moulu 25kg', 'Curcuma sacs 10kg', 'Ras el hanout vrac', 'Harissa cartons'],
      locations: ['Guangzhou', 'Yiwu'],
    },
    {
      id: 'hygiene-entretien',
      name: 'Hygiène & Entretien',
      icon: '🧹',
      description: 'Produits ménagers, lessives, éponges, papier toilette en gros',
      priceRange: '0.30-4€',
      moq: 500,
      margin: '×2.5 à ×4',
      topProducts: ['Javel cartons 24', 'Éponges lots 100', 'Liquide vaisselle 5L', 'Sacs poubelle rouleaux'],
      locations: ['Guangzhou', 'Yiwu'],
    },
  ],

  // ═══════════════════════════════════════════
  // DÉTAILLANT — Boutique, petites séries, adapté terrain
  // ═══════════════════════════════════════════
  detaillant: [
    {
      id: 'boucherie-halal',
      name: 'Boucherie Halal',
      icon: '🥩',
      description: 'Équipements boucherie, couteaux pro, emballages, vitrines, épices viande',
      priceRange: '2-30€',
      moq: 50,
      margin: '×2 à ×4',
      topProducts: ['Couteaux boucher pro', 'Papier boucherie imprimé', 'Épices merguez/kefta', 'Barquettes viande'],
      locations: ['Yiwu', 'Guangzhou'],
    },
    {
      id: 'epicerie-orientale',
      name: 'Épicerie Orientale',
      icon: '🫒',
      description: 'Produits secs, conserves, boissons, confiserie orientale, thé',
      priceRange: '0.50-6€',
      moq: 100,
      margin: '×2 à ×3.5',
      topProducts: ['Thé à la menthe cartons', 'Dattes Medjool', 'Eau de rose', 'Loukoums assortis'],
      locations: ['Yiwu', 'Guangzhou'],
    },
    {
      id: 'textile-boutique',
      name: 'Textile & Mode Modeste',
      icon: '🧕',
      description: 'Abayas, hijabs, djellabas, qamis, vêtements modestes prêt-à-porter',
      priceRange: '5-25€',
      moq: 30,
      margin: '×2.5 à ×5',
      topProducts: ['Abayas collection', 'Hijabs premium soie', 'Qamis homme', 'Robes orientales fête'],
      locations: ['Guangzhou'],
    },
    {
      id: 'cosmetique-naturel',
      name: 'Cosmétique Naturel',
      icon: '🌿',
      description: 'Huile d\'argan, savon noir, henné, musc, parfums orientaux',
      priceRange: '1-12€',
      moq: 50,
      margin: '×3 à ×6',
      topProducts: ['Huile d\'argan 100ml', 'Musc tahara', 'Savon noir beldi', 'Coffrets hammam'],
      locations: ['Guangzhou', 'Yiwu'],
    },
    {
      id: 'decoration-interieur',
      name: 'Décoration intérieur',
      icon: '🏠',
      description: 'Calligraphie arabe, lanternes, tapis, coussins, ambiance orientale',
      priceRange: '2-20€',
      moq: 30,
      margin: '×3 à ×5',
      topProducts: ['Cadres calligraphie', 'Lanternes métal', 'Tapis prière luxe', 'Brûle-encens'],
      locations: ['Yiwu'],
    },
    {
      id: 'articles-religieux',
      name: 'Articles Religieux',
      icon: '🕌',
      description: 'Tapis de prière, chapelets, Corans, tenues Hajj/Omra, calendriers',
      priceRange: '1-15€',
      moq: 50,
      margin: '×3 à ×6',
      topProducts: ['Tapis prière velours', 'Chapelets (misbaha)', 'Porte-Coran bois', 'Packs Omra complets'],
      locations: ['Yiwu'],
    },
    {
      id: 'vaisselle-ustensiles',
      name: 'Vaisselle & Ustensiles',
      icon: '🍵',
      description: 'Services à thé, tajines, théières, plateaux, verres marocains',
      priceRange: '2-18€',
      moq: 50,
      margin: '×2.5 à ×4',
      topProducts: ['Services thé marocain', 'Tajines céramique', 'Théières inox', 'Verres à thé dorés'],
      locations: ['Yiwu', 'Guangzhou'],
    },
    {
      id: 'confiserie-patisserie',
      name: 'Confiserie & Pâtisserie',
      icon: '🍯',
      description: 'Cornes de gazelle, baklavas, nougat, halwa, moules pâtisserie orientale',
      priceRange: '1-8€',
      moq: 100,
      margin: '×2.5 à ×4',
      topProducts: ['Moules makrout', 'Plateaux pâtisserie', 'Pistaches vrac', 'Eau de fleur oranger'],
      locations: ['Yiwu', 'Guangzhou'],
    },
  ],

  // ═══════════════════════════════════════════
  // E-COMMERCE — Trending, branding, forte marge
  // ═══════════════════════════════════════════
  ecommerce: [
    {
      id: 'gadgets-trending',
      name: 'Gadgets Tendance',
      icon: '🔥',
      description: 'Produits viraux TikTok, gadgets innovants, winner products à forte marge',
      priceRange: '1-8€',
      moq: 50,
      margin: '×5 à ×10',
      topProducts: ['Sunset lamp', 'Mini projecteur', 'Nettoyeur ultrason bijoux', 'Lampe lune 3D'],
      locations: ['Shenzhen', 'Yiwu'],
    },
    {
      id: 'accessoires-tech',
      name: 'Accessoires Tech',
      icon: '📱',
      description: 'Coques, câbles, supports, chargeurs sans fil, accessoires PC/gaming',
      priceRange: '0.50-6€',
      moq: 50,
      margin: '×5 à ×12',
      topProducts: ['Coques iPhone custom', 'Chargeurs MagSafe', 'Hub USB-C', 'Lampe écran LED'],
      locations: ['Shenzhen'],
    },
    {
      id: 'bijoux-fantaisie',
      name: 'Bijoux & Accessoires',
      icon: '💎',
      description: 'Acier inoxydable, plaqué or, perles, bracelets personnalisés, packaging premium',
      priceRange: '0.50-5€',
      moq: 30,
      margin: '×6 à ×15',
      topProducts: ['Bagues acier 316L', 'Colliers prénom', 'Bracelets perles', 'Coffrets cadeau'],
      locations: ['Yiwu'],
    },
    {
      id: 'cosmetique-niche',
      name: 'Cosmétique Niche',
      icon: '✨',
      description: 'Sérums, masques, outils beauté, packaging luxe, marque blanche possible',
      priceRange: '1-8€',
      moq: 100,
      margin: '×4 à ×8',
      topProducts: ['Sérum vitamine C', 'Gua sha jade', 'Masques collagène', 'Roller quartz rose'],
      locations: ['Guangzhou'],
    },
    {
      id: 'fitness-wellness',
      name: 'Fitness & Bien-être',
      icon: '🧘',
      description: 'Bandes élastiques, tapis yoga, masseurs, bouteilles sport, accessoires gym',
      priceRange: '1-10€',
      moq: 50,
      margin: '×4 à ×7',
      topProducts: ['Bandes résistance set', 'Tapis yoga TPE', 'Pistolet massage mini', 'Bouteille motivante'],
      locations: ['Yiwu', 'Guangzhou'],
    },
    {
      id: 'maison-deco',
      name: 'Maison & Déco',
      icon: '🏡',
      description: 'LED déco, organisateurs, bougies, cadres, objets déco tendance',
      priceRange: '1-12€',
      moq: 30,
      margin: '×3 à ×6',
      topProducts: ['Néon LED custom', 'Organisateur tiroir', 'Bougies parfumées', 'Miroir LED'],
      locations: ['Yiwu', 'Shenzhen'],
    },
    {
      id: 'mode-accessoires',
      name: 'Mode & Accessoires',
      icon: '👜',
      description: 'Sacs, lunettes, montres, casquettes, foulards — forte marge branding',
      priceRange: '2-15€',
      moq: 30,
      margin: '×4 à ×8',
      topProducts: ['Sacs crossbody', 'Lunettes soleil trendy', 'Montres minimalistes', 'Casquettes brodées'],
      locations: ['Guangzhou', 'Yiwu'],
    },
    {
      id: 'enfants-jouets',
      name: 'Enfants & Jouets',
      icon: '🧸',
      description: 'Jouets éducatifs, peluches, jeux créatifs, articles bébé, livres activités',
      priceRange: '1-10€',
      moq: 50,
      margin: '×3 à ×6',
      topProducts: ['Busy board Montessori', 'Kit slime DIY', 'Peluches custom', 'Puzzles bois éducatifs'],
      locations: ['Yiwu', 'Shenzhen'],
    },
  ],
  // ═══════════════════════════════════════════
  // PRO / BTP — Matériaux, chantier, gros volumes
  // ═══════════════════════════════════════════
  pro: [
    {
      id: 'fenetres-menuiserie',
      name: 'Fenêtres & Menuiserie',
      icon: '🪟',
      description: 'Fenêtres PVC/alu, portes, volets roulants, double vitrage, baies vitrées',
      priceRange: '25-200€',
      moq: 50,
      margin: '×1.8 à ×3',
      topProducts: ['Fenêtres PVC double vitrage', 'Baies vitrées coulissantes', 'Volets roulants alu', 'Portes d\'entrée blindées'],
      locations: ['Guangzhou', 'Foshan'],
    },
    {
      id: 'materiaux-construction',
      name: 'Matériaux de Construction',
      icon: '🧱',
      description: 'Carrelage, faïence, ciment colle, plaques, panneaux, isolation thermique',
      priceRange: '2-30€',
      moq: 200,
      margin: '×1.5 à ×2.5',
      topProducts: ['Carrelage 60×60 palettes', 'Faïence murale lots', 'Colle carrelage tonnes', 'Panneaux isolation'],
      locations: ['Foshan', 'Guangzhou'],
    },
    {
      id: 'outillage-pro',
      name: 'Outillage Professionnel',
      icon: '🔧',
      description: 'Perceuses, meuleuses, compresseurs, échafaudages, outils à main pro',
      priceRange: '8-80€',
      moq: 50,
      margin: '×2 à ×3.5',
      topProducts: ['Perceuses sans fil', 'Meuleuses 230mm', 'Coffrets outils complets', 'Échafaudages roulants'],
      locations: ['Yongkang', 'Guangzhou'],
    },
    {
      id: 'sanitaire-plomberie',
      name: 'Sanitaire & Plomberie',
      icon: '🚿',
      description: 'Robinetterie, WC, lavabos, tuyaux, raccords, chauffe-eau, douches',
      priceRange: '5-120€',
      moq: 50,
      margin: '×2 à ×3',
      topProducts: ['Robinets mitigeurs', 'WC suspendus', 'Lavabos vasque', 'Colonnes de douche'],
      locations: ['Foshan', 'Kaiping'],
    },
    {
      id: 'electricite-eclairage',
      name: 'Électricité & Éclairage',
      icon: '💡',
      description: 'Spots LED, panneaux LED, câbles, tableaux électriques, luminaires industriels',
      priceRange: '1-50€',
      moq: 100,
      margin: '×2.5 à ×4',
      topProducts: ['Spots encastrables LED', 'Panneaux LED 60×60', 'Réglettes néon LED', 'Projecteurs chantier'],
      locations: ['Zhongshan', 'Shenzhen'],
    },
    {
      id: 'revetements-sols',
      name: 'Revêtements de Sol',
      icon: '🏗️',
      description: 'Parquet flottant, vinyle LVT, moquette, gazon synthétique, résine',
      priceRange: '3-25€',
      moq: 200,
      margin: '×1.8 à ×3',
      topProducts: ['Parquet stratifié palettes', 'Sol vinyle LVT clipsable', 'Gazon synthétique rouleaux', 'Plinthe assortie lots'],
      locations: ['Changzhou', 'Guangzhou'],
    },
    {
      id: 'quincaillerie-gros',
      name: 'Quincaillerie en Gros',
      icon: '🔩',
      description: 'Vis, boulons, charnières, serrures, poignées, accessoires porte/fenêtre',
      priceRange: '0.05-8€',
      moq: 1000,
      margin: '×2.5 à ×5',
      topProducts: ['Vis inox cartons 10000', 'Serrures multipoints', 'Poignées de porte lots', 'Charnières invisibles'],
      locations: ['Yiwu', 'Jieyang'],
    },
    {
      id: 'securite-epi',
      name: 'Sécurité & EPI',
      icon: '🦺',
      description: 'Casques chantier, gants, chaussures sécurité, gilets, harnais, extincteurs',
      priceRange: '1-25€',
      moq: 100,
      margin: '×2.5 à ×4',
      topProducts: ['Casques chantier CE', 'Chaussures sécurité S3', 'Gants travail lots', 'Gilets haute visibilité'],
      locations: ['Guangzhou', 'Yiwu'],
    },
  ],
}

// Helper: récupérer le catalogue d'un profil
export const getCatalog = (tierKey) => CATALOGS[tierKey] || CATALOGS.detaillant

// Helper: récupérer une catégorie spécifique dans un catalogue
export const getCategoryFromCatalog = (tierKey, categoryId) =>
  getCatalog(tierKey).find(cat => cat.id === categoryId)
