// ─── CARAXES PRODUCT CATEGORIES ───
// 10 catégories sourcing Chine → France, basées sur le guide CARAXES

export const CATEGORIES = [
  {
    id: 'enceintes-bluetooth',
    name: 'Enceintes Bluetooth',
    description: 'Enceintes portables, haut-parleurs sans fil, barres de son',
    icon: '🔊',
    color: '#E63946',
    priceChina: '6-10€',
    priceFrance: '25-45€',
    margin: '×3 à ×5',
    notes: 'Certifications CE obligatoires. Privilégier modèles étanches IPX5+.',
    locations: ['Shenzhen', 'Guangzhou'],
  },
  {
    id: 'coques-telephone',
    name: 'Coques Téléphone',
    description: 'Coques iPhone, Samsung, personnalisées, silicone, cuir',
    icon: '📱',
    color: '#D4A843',
    priceChina: '0.30-1€',
    priceFrance: '8-15€',
    margin: '×10+',
    notes: 'Machine impression UV ~200€ ou fournisseur print-on-demand.',
    locations: ['Shenzhen', 'Yiwu'],
  },
  {
    id: 'accessoires-fitness',
    name: 'Accessoires Fitness',
    description: 'Bandes élastiques, poignées, tapis yoga, haltères',
    icon: '💪',
    color: '#4ECDC4',
    priceChina: '1-5€',
    priceFrance: '15-35€',
    margin: '×4 à ×7',
    notes: 'Qualité du latex variable. Inspection obligatoire.',
    locations: ['Yiwu', 'Guangzhou'],
  },
  {
    id: 'bijoux-fantaisie',
    name: 'Bijoux Fantaisie',
    description: 'Acier inoxydable 316L, argent, plaqué or, hypoallergénique',
    icon: '💎',
    color: '#C77DFF',
    priceChina: '0.50-3€',
    priceFrance: '10-30€',
    margin: '×5 à ×10',
    notes: 'Acier 316L hypoallergénique = argument fort. Yiwu = meilleur marché.',
    locations: ['Yiwu'],
  },
  {
    id: 'gadgets-cuisine',
    name: 'Gadgets Cuisine',
    description: 'Éplucheurs, moules silicone, ustensiles, rangement cuisine',
    icon: '🍳',
    color: '#FF6B35',
    priceChina: '0.50-3€',
    priceFrance: '8-20€',
    margin: '×4 à ×7',
    notes: 'Certification alimentaire obligatoire pour silicone (LFGB ou FDA).',
    locations: ['Yiwu', 'Guangzhou'],
  },
  {
    id: 'eclairage-led',
    name: 'Éclairage LED',
    description: 'Néons LED, sunset lamps, guirlandes, éclairage décoratif',
    icon: '💡',
    color: '#FFD700',
    priceChina: '2-8€',
    priceFrance: '15-40€',
    margin: '×3 à ×5',
    notes: 'Néons LED personnalisables et sunset lamps très demandés en 2026.',
    locations: ['Shenzhen', 'Guangzhou'],
  },
  {
    id: 'organisateurs-rangement',
    name: 'Organisateurs & Rangement',
    description: 'Boîtes, tiroirs, rangement bureau, dressing, salle de bain',
    icon: '📦',
    color: '#8B9DAF',
    priceChina: '1-5€',
    priceFrance: '10-25€',
    margin: '×3 à ×5',
    notes: 'Produits légers = frais de port réduits. Bon ratio poids/marge.',
    locations: ['Yiwu'],
  },
  {
    id: 'accessoires-animaux',
    name: 'Accessoires Animaux',
    description: 'Jouets chien/chat, laisses, gamelles, vêtements animaux',
    icon: '🐾',
    color: '#FF8C42',
    priceChina: '1-6€',
    priceFrance: '12-30€',
    margin: '×3 à ×5',
    notes: 'Marché en forte croissance. Propriétaires dépensent sans compter.',
    locations: ['Yiwu', 'Guangzhou'],
  },
  {
    id: 'papeterie-creative',
    name: 'Papeterie Créative',
    description: 'Carnets, calligraphie, stickers, washi tape, journaling',
    icon: '✏️',
    color: '#E0AAFF',
    priceChina: '0.20-2€',
    priceFrance: '5-15€',
    margin: '×5 à ×8',
    notes: 'Carnets personnalisés et sets calligraphie = best-sellers Etsy.',
    locations: ['Yiwu'],
  },
  {
    id: 'accessoires-tech',
    name: 'Accessoires Tech',
    description: 'Câbles, supports, hubs USB, chargeurs, accessoires PC',
    icon: '🔌',
    color: '#00B4D8',
    priceChina: '1-5€',
    priceFrance: '10-25€',
    margin: '×3 à ×5',
    notes: 'Qualité variable. Toujours tester un échantillon avant commande.',
    locations: ['Shenzhen'],
  },
]

export const getCategoryById = (id) => CATEGORIES.find(c => c.id === id)
export const getCategoryColor = (id) => getCategoryById(id)?.color || '#D4A843'
